config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :articles do
    resources :comments
  end
  # , only: [:new]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 10 }
  has_one_attached :photo
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :photo, dependent: :destroy

  validates :username, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :photo)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>Articles</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
        <p> <%= Article.count %> articles</p>
    </div>
  </div>

  <div class="row">
    <% @articles.each do |article| %>
      <div class="col-6">
          <div class="card-article p-3">
            <%= cl_image_tag article.photo.key %>
            <div class="card-article-infos d-flex align-items-center justify-content-between">
              <div>
                <h2 class="mr-3"><%= article.title %></h2>
                <p class="mr-3"><%= article.description %></p>
                <p><%= link_to "Lire l'article", article_path(article), class: "btn btn-ghost" %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/articles/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>sélection: <%= @article.title %></h1>
    </div>
  </div>

  <div class="row">
    <div class="col-12 py-3">
      <div class="big-card-article">
        <%= cl_image_tag @article.photo.key %>
        <div class="card-article-infos d-flex align-items-center justify-content-between p-5 m-5">
          <div>
            <h2 class="mr-3"><%= @article.title %></h2>
          </div>
        </div>
        <div class="flex align-items-center mx-5 mb-5" style="text-align: center">
            <h4><%= @article.content  %></h4>
        </div>
    </div>`
  </div>

  <div class="col-6">
    <div class="big-card-article p-4">
      <h5>Réserve ce vélo!</h5>

      <form action="">
        <div class="input-group">
          <span class="input-group-text" id="start-date-label">du:</span>
          <input type="text" class="form-control" placeholder="12/10/2017" aria-label="start-date" aria-describedby="start-date-label">
        </div>
        <div class="input-group mt-2">
          <span class="input-group-text" id="end-date-label">au:</span>
          <input type="text" class="form-control" placeholder="18/10/2017" aria-label="end-date" aria-describedby="start-date-label">
        </div>
        <input type="submit" value="Réserver" class="btn big-btn-ghost mt-2" style="width: 100%">
      </form>
    </div>
  </div>


  <div class="row">
    <div class="col-12">
      <p><%= link_to "       Je réserve ce vélo maintenant      ", root_path, class: "d-flex justify-content-center mx-5 btn big-btn-ghost" %></p>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeBlogRevisions</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
      <div class="logo"><%= image_tag("logo_m.png", alt: "Logo", id: "logo-img") %></div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= cl_image_tag current_user.photo.key, class: "avatar-image" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Home", root_path, class: "nav_link dropdown-item" %>
              <%= link_to "Index", articles_path, class: "nav_link dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>